name: CI

on: [push]

env:
  CI: true
  NODE_ENV: test
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 12.x

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Node.js dependencies
      if: "steps.yarn-cache.outputs.cache-hit != 'true'"
      run: yarn --frozen-lockfile


    - name: Build
      run: tsc && yarn build

    - name: Tests
      run: yarn test


    - name: Benchmark
      run: yarn benchmark

